language: android
dist: trusty

git:
  submodules: false

android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra

before_install:
  - sudo apt-get update
  - sudo apt-get -y install ninja-build

install:
  - echo y | sdkmanager "ndk-bundle"

before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - ./build_app_in_ci.sh
