language: android
dist: trusty
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra

install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
  - echo y | sdkmanager "lldb;3.1"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - ./build_app_in_ci.sh
