language: android
dist: xenial

git:
  submodules: false

android:
  components:
    - build-tools-29.0.2
    - android-29


before_install:
  - sudo apt-get update
  - sudo apt-get -y install ninja-build

cache:
  - $TRAVIS_BUILD_DIR/ThirdParty

env:
  - BUILD_TARGET=assembleBasicRelease
  - BUILD_TARGET=test

install:
  - echo $TRAVIS_BUILD_DIR
  - echo $HOME
  - ./scripts/build_and_install_swig.sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/ThirdParty/swig-4.0.1/install/bin
  - swig -version
  - echo y | sdkmanager "ndk-bundle"

before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - git submodule update --init --recursive
  - "./gradlew $BUILD_TARGET"
